translation-api:
  base_url: https://api-translate.systran.net/translation
  text_url: https://api-translate.systran.net/translation/text/translate
  profiles_url: https://api-translate.systran.net/translation/profiles
  key: a3e8bfaf-32e2-4055-a68b-d5283805951d
logging:
  level:
    org:
      springframework:
        web:
          filter.CommonsRequestLoggingFilter: DEBUG
spring:
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.H2Dialect
      database-platform: org.hibernate.dialect.H2Dialect
    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: root
      password: root
    h2:
      console:
        enabled: true
        path: /h2-console
        settings:
          trace: false
          web-allow-others: true